FROM mysql
ENV MYSQL_ROOT_PASSWORD NawafPass
ENV MYSQL_DATABASE NawafDB
ENV MYSQL_USER NawafUser
ENV MYSQL_PASSWORD NawafPass
#EXPOSE 3306
WORKDIR /home/
#COPY ./ContainerFiles/ .
#ENTRYPOINT ["chmod" + "+777" + "InsertToDB.sh"]
#CMD ["chmod" + "+777" + "InsertToDB.sh"+ " &&" + "./InsertToDB.sh"]
#RUN ["mysql" + "-uNawafUser" + "-pNawafPass" + "<" + "setup.sql"]
#CMD ["source" + "setup.sh"]
